### ISSUE TITLE
Css class generation bug

### ISSUE THREAD

**Issue by k206i** [Dazix/SimpleCountDown#11]
extra "_" character in js
![image](https://user-images.githubusercontent.com/20324335/88644984-45bad780-d0cc-11ea-81b3-96955a6123ef.png)

mismatch with less
![image](https://user-images.githubusercontent.com/20324335/88645281-9df1d980-d0cc-11ea-9ac4-4c78d44cce55.png)
![image](https://user-images.githubusercontent.com/20324335/88645462-d0033b80-d0cc-11ea-96d8-2aec0408a899.png)

**Comment by Dazix** [comment]
Thanks for report
