### ISSUE TITLE
Doesn't seem like one can use a date object for date

### ISSUE THREAD

**Issue by RobertoJBeltran** [Dazix/SimpleCountDown#3]
making a new date object like in the documentation doesn't seem to work. Although making a date object and getting the time works like so:

```
    ...
    date: new Date(1583468400000).getTime(),
    ...
```

or more usefully:

```
    ...
    date: new Date("Dec 24 2020").getTime(),
    ...
```

**Comment by Dazix** [comment]
Thanks for reporting
